name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          DB_HOST=localhost
          DB_PORT=3306
          DB_USER=user
          DB_PASS=root
          DB_NAME=test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        
      - name: Run build
        run: pnpm run build

      - name: Run lint
        run: pnpm run lint

      - name: Run unit tests
        run: pnpm run test
      
      - name: Wait for MySQL to be ready
        run: |
          for i in {30..0}; do
            if mysqladmin ping -h127.0.0.1 -P3306 --silent; then
              break
            fi
            echo 'MySQL not ready yet...'
            sleep 1
          done
          if [ $i -eq 0 ]; then
            echo 'MySQL did not start within the expected time.'
            exit 1
              fi
      - name: Run integration tests 
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_USER: user
          DB_PASS: root
          DB_NAME: test
        run: pnpm run test:e2e
